### ISSUE TITLE
Should handle missing "function" field

### ISSUE THREAD

**Issue by lissyx** [mozilla/fx-crash-sig#72]
From telemetry crash ping, I found that and when trying to get a signature for this:
```
{"payload": {"stack_traces":{"crash_info":{"address":"0x10e","crashing_thread":0,"type":"SIGSYS"},"main_module":0,"modules":[{"base_addr":"0x55fb90db8000","code_id":"03e9a066eea4752d95afd8be68a33b5d37ea0414","debug_file":"firefox-bin","debug_id":"66A0E903A4EE2D7595AFD8BE68A33B5D0","end_addr":"0x55fb90e7f000","filename":"firefox-bin","version":""},{"base_addr":"0x7f841701f000","code_id":"0401bd8da6edab3e45399d62571357ab12545133","debug_file":"libc.so.6","debug_id":"8DBD0104EDA63EAB45399D62571357AB0","end_addr":"0x7f84171f3000","filename":"libc.so.6","version":""},{"base_addr":"0x7f84175a5000","code_id":"d6f505180a9d542c1d37c1be618f4c4e4171819c","debug_file":"libproxychains.so.4","debug_id":"1805F5D69D0A2C541D37C1BE618F4C4E0","end_addr":"0x7f84175b2000","filename":"libproxychains.so.4","version":""},{"base_addr":"0x7f8417617000","code_id":"4286bd11475e673b194ee969f5f9e9759695e644","debug_file":"ld-linux-x86-64.so.2","debug_id":"11BD86425E473B67194EE969F5F9E9750","end_addr":"0x7f841764b000","filename":"ld-linux-x86-64.so.2","version":""}],"status":"OK","threads":[{"ip":null,"module_index":null,"trust":null,"frames":[{"ip":"0x7f841711d77c","module_index":1,"trust":"context"},{"ip":"0x7f84175ace62","module_index":2,"trust":"scan"},{"ip":"0x55fb90dbcc2b","module_index":0,"trust":"scan"},{"ip":"0x7f841764a667","module_index":3,"trust":"scan"},{"ip":"0x7f841764a2df","module_index":3,"trust":"scan"},{"ip":"0x7f8417620b37","module_index":3,"trust":"scan"},{"ip":"0x7f841764a2df","module_index":3,"trust":"scan"},{"ip":"0x7f841764a667","module_index":3,"trust":"scan"},{"ip":"0x7f841703513f","module_index":1,"trust":"scan"},{"ip":"0x7f841764a2df","module_index":3,"trust":"scan"},{"ip":"0x55fb90e7e1cf","module_index":0,"trust":"scan"},{"ip":"0x7f8417626fad","module_index":3,"trust":"scan"},{"ip":"0x7f841703513f","module_index":1,"trust":"scan"},{"ip":"0x7f84170a473f","module_index":1,"trust":"scan"},{"ip":"0x7f84175ad13f","module_index":2,"trust":"scan"},{"ip":"0x7f8417629299","module_index":3,"trust":"scan"},{"ip":"0x7f841705b756","module_index":1,"trust":"scan"},{"ip":"0x7f84170a3dc6","module_index":1,"trust":"scan"},{"ip":"0x7f841716de9e","module_index":1,"trust":"scan"},{"ip":"0x7f841764901f","module_index":3,"trust":"scan"},{"ip":"0x7f84175ad13f","module_index":2,"trust":"scan"},{"ip":"0x7f84175ad03b","module_index":2,"trust":"scan"},{"ip":"0x7f84175ad172","module_index":2,"trust":"scan"},{"ip":"0x55fb90e2bb33","module_index":0,"trust":"scan"},{"ip":"0x7f84175ad13f","module_index":2,"trust":"scan"},{"ip":"0x55fb90e6524e","module_index":0,"trust":"scan"},{"ip":"0x7f84175ad13f","module_index":2,"trust":"scan"},{"ip":"0x7f84170a7fd3","module_index":1,"trust":"scan"},{"ip":"0x7f84170a7d0f","module_index":1,"trust":"scan"},{"ip":"0x7f84171285bb","module_index":1,"trust":"scan"}]}],"unloaded_modules":[]}}}
```

It crashes with:
```
Traceback (most recent call last):
  File "/home/alex/.local/bin/fx-crash-sig", line 8, in <module>
    sys.exit(cmdline())
             ^^^^^^^^^
  File "/home/alex/.local/lib/python3.11/site-packages/fx_crash_sig/cmd_get_crash_sig.py", line 42, in cmdline
    result = crash_processor.get_signature(payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.local/lib/python3.11/site-packages/fx_crash_sig/crash_processor.py", line 40, in get_signature
    print(f"   {frame['frame']}    {frame['function']}")
                                    ~~~~~^^^^^^^^^^^^
KeyError: 'function'
```

Hacking the code to `elif` and just `print()` with only `frame['frame']` gets me some output:
```
Symbolicated stack:
   0    __select
   1
   2
   3
   4
   5    _dl_lookup_symbol_x
   6
   7
   8
   9
   10    _fini
   11    _dl_fixup
   12
   13    __pthread_disable_asynccancel
   14
   15    _dl_runtime_resolve_xsavec
   16    __GI_sigaltstack
   17    _dlerror_run
   18    _dl_catch_error
   19
   20
   21
   22
   23    free
   24
   25    set_alt_signal_stack_and_start(PthreadCreateParams*)
   26
   27    start_thread
   28    create_thread
   29    __clone3
signature: __select
notes:     (0)
```

**Comment by willkg** [comment]
Oh, whoops--that's lousy. I'll try to fix this this week.

**Comment by willkg** [comment]
I did a 1.0.1 release picking up this fix. https://pypi.org/project/fx-crash-sig/1.0.1/
